version: "3.3"
services:
  
  airvisor:
    image: airvisor
    build:
      context: ./airvisor
      dockerfile: Dockerfile
    volumes:
    - ./airvisor:/app
    - /app/node_modules
    ports:
    - 3001:3001
    environment:
    - CHOKIDAR_USEPOLLING=true

  crossbar_router:
    image: "crossbario/crossbar"
    ports: 
      - "8080:8080"
    volumes: 
      - "./crossbar_router:/node"
    user: "0"

  instrument1_service:
    image: instrument1_service
    build:
      context: ./instrument1_service
      dockerfile: Dockerfile
    environment: 
      - CBURL=ws://crossbar_router:8080/ws
      - CBREALM=realm1
      - CBTOPIC=com.myapp.hello/instrument1
    volumes: 
      - "./instrument1_service:/app"
    command: python -u /app/mock_component/client_component_publish.py
    
  instrument1_mfe:
    image: instrument1_mfe
    build:
      context: ./instrument1_mfe
      dockerfile: Dockerfile
    volumes:
    - ./instrument1_mfe:/app
    - /app/node_modules
    ports:
    - 3002:3002
    environment:
    - CHOKIDAR_USEPOLLING=true