version: "3.3"
services:
  
  composite-ui:
    build: ./composite-ui
    image: "composite-ui:compose-build-v1"
    ports:
      - "3001:3001"
    volumes: 
      - "./composite-ui/src:/usr/src/composite-ui/src"

  crossbar-router:
    image: "crossbario/crossbar"
    ports: 
      - "8080:8080"
    volumes: 
      - "./crossbar-router:/node"
    user: "0"

  instrument1-service:
    image: "crossbario/autobahn-python:cpy3"
    environment: 
      - CBURL=ws://crossbar-router:8080/ws
      - CBREALM=realm1
      - CBTOPIC=com.myapp.hello/instrument1
    volumes: 
      - "./instrument1-service:/app"
    command: python /app/mock_component/client_component_publish.py
    
  instrument1-mfe:
    build: ./instrument1-mfe
    image: "instrument1-mfe:compose-build-v1"
    ports:
      - "3002:3002"
    volumes: 
      - "./instrument1-mfe/src:/usr/src/mfe1/src"

  instrument2-service:
    image: "crossbario/autobahn-python:cpy3"
    environment: 
      - CBURL=ws://crossbar-router:8080/ws
      - CBREALM=realm1
      - CBTOPIC=com.myapp.hello/instrument2
    volumes: 
      - "./instrument2-service:/app"
    command: python /app/mock_component/client_component_publish.py
    
  instrument2-mfe:
    build: ./instrument2-mfe
    image: "instrument2-mfe:compose-build-v1"
    ports:
      - "3003:3003"
    volumes: 
      - "./instrument2-mfe/src:/usr/src/mfe2/src"