version: "3.3"
services:
  
  airvisor:
    image: airvisor
    build:
      context: ./airvisor
      dockerfile: Dockerfile
    volumes:
    - ./airvisor:/app
    - /app/node_modules
    ports:
    - 3001:3001
    environment:
    - CHOKIDAR_USEPOLLING=true

  crossbar_router:
    image: "crossbario/crossbar"
    ports: 
      - "8080:8080"
    volumes: 
      - "./crossbar_router:/node"
    user: "0"

  imu_service:
    image: imu_service
    build:
      context: ./imu_service
      dockerfile: Dockerfile
    volumes: 
      - "./imu_service:/app"
    command: python -u /app/service.py
    
  imu_mfe:
    image: imu_mfe
    build:
      context: ./imu_mfe
      dockerfile: Dockerfile
    volumes:
    - ./imu_mfe:/app
    - /app/node_modules
    ports:
    - 3002:3002
    environment:
    - CHOKIDAR_USEPOLLING=true

  acc_service:
    image: acc_service
    build:
      context: ./acc_service
      dockerfile: Dockerfile
    volumes: 
      - "./acc_service:/app"
    command: python -u /app/service.py
    
  acc_mfe:
    image: acc_mfe
    build:
      context: ./acc_mfe
      dockerfile: Dockerfile
    volumes:
    - ./acc_mfe:/app
    - /app/node_modules
    ports:
    - 3003:3003
    environment:
    - CHOKIDAR_USEPOLLING=true