version: "3.3"
services:

  composite-ui:
    image: "node:10"
    ports:
      - "3001:3001"
    volumes: 
      - "./composite-ui:/usr/src/composite-ui"
    working_dir: "/usr/src/composite-ui"
    command: yarn start

  crossbar-router:
    image: "crossbario/crossbar"
    ports: 
      - "8080:8080"
    volumes: 
      - "./crossbar-router:/node"
    user: "0"

  instrument1-service:
    image: "crossbario/autobahn-python:cpy3"
    environment: 
      - CBURL=ws://crossbar-router:8080/ws
      - CBREALM=realm1
    volumes: 
      - "./instrument1-service:/app"
    command: python /app/1.hello-world/client_component_publish.py

  instrument1-mfe:
    image: "node:10"
    ports:
      - "3002:3002"
    volumes:
      - "./instrument1-mfe:/usr/src/mfe1"
    working_dir: "/usr/src/mfe1"
    command: yarn start 

  