version: "3.3"
services:

  composite-ui:
    image: "composite-ui:v2"
    ports:
      - "3001:3001"

  crossbar-router:
    image: "crossbario/crossbar"
    ports: 
      - "8080:8080"
    volumes: 
      - "./crossbar-router:/node"
    user: "0"

  instrument1-service:
    image: "crossbario/autobahn-python:cpy3"
    environment: 
      - CBURL=ws://crossbar-router:8080/ws
      - CBREALM=realm1
    volumes: 
      - "./instrument1-service:/app"
    command: python /app/1.hello-world/client_component_publish.py

  instrument1-mfe:
    image: "instrument1-mfe:v2"
    ports:
      - "3002:3002"
  