version: '3.7'
services:
  acc_mfe:
    image: acc_mfe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - '3003:3003'
    environment:
      - CHOKIDAR_USEPOLLING=true
