version: '3.7'
services:
  prototype_cui:
    image: prototype_cui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - '3001:3001'
    environment:
      - CHOKIDAR_USEPOLLING=true
